import json
from datetime import datetime
from app.core.supabase import db

# 1. THE MAPPING DICTIONARY (CSV Name -> Database Name)
NAME_MAP = {
    "TamponTribe.com": "Tampon Tribe",
    "zodiaksmoonrock.com (part of BellaSoftCBD)": "ZodiaksMoonRock",
    "bellasoftcbd.com": "BellaSoftCBD",
    "drinkmimosa.com": "Mimosa Royale",
    "Amor Sui": "AmorSui",
    "snazzybeverages.com": "Snazzy Beverages",
    "AnaOno.com": "AnaOno",
    "CaireBeauty.com": "Caire Beauty",
    "dirtydill.com": "Dirty Dill",
    "filamanila.com": "Fila Manila",
    "MiamiBeachBum.com": "Miami Beach Bum",
    "Misscommando.com": "Miss Commando",
    "untoxicated.com": "Untoxicated",
    "FreshPeaches.co": "Fresh Peaches",
    "okuenergy.com": "OKU",
    "AVVIKA": "Avvika",
    "Shield-Wallet.com": "Shield Wallet" 
}

# 2. YOUR DATA (From CSV)
tracker_data = [
    {'client_name': 'AVVIKA', 'owner': 'U07RN86AUN7', 'developer': 'U08PG0X0ES0', 'launch_date_internal': '2025-08-22', 'launch_date_public': '2025-08-31', 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': True, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': True, 'Data Migration Completed': False, 'Theme Migration Started': True, 'Theme Migration Completed': True, 'App Setup Started': True, 'App Setup Completed': True, 'GA4 Access': True, 'GA4 Setup': True, 'GTM Access': True, 'GTM Setup': True, 'Other Pixels': True, 'CDN Access': True, 'Ready to go Live': True, 'Notifications turned on': True}},
    {'client_name': 'Drink Yate', 'owner': 'U0838K7CZJP', 'developer': 'U08PG0X0ES0', 'launch_date_internal': None, 'launch_date_public': None, 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': False, 'Store Setup': False, 'Access Sent': False, 'Data Migration Started': False, 'Data Migration Completed': False, 'Theme Migration Started': False, 'Theme Migration Completed': False, 'App Setup Started': False, 'App Setup Completed': False, 'GA4 Access': False, 'GA4 Setup': False, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'Boozy Jerky', 'owner': 'leo@flyrank.com', 'developer': None, 'launch_date_internal': None, 'launch_date_public': None, 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': False, 'Deliverables Completed': False, 'Store Setup': False, 'Access Sent': False, 'Data Migration Started': False, 'Data Migration Completed': False, 'Theme Migration Started': False, 'Theme Migration Completed': False, 'App Setup Started': False, 'App Setup Completed': False, 'GA4 Access': False, 'GA4 Setup': False, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'Mixed Up Clothing', 'owner': 'leo@flyrank.com', 'developer': None, 'launch_date_internal': None, 'launch_date_public': None, 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': False, 'Store Setup': False, 'Access Sent': False, 'Data Migration Started': False, 'Data Migration Completed': False, 'Theme Migration Started': False, 'Theme Migration Completed': False, 'App Setup Started': False, 'App Setup Completed': False, 'GA4 Access': False, 'GA4 Setup': False, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'PiperWai', 'owner': 'leo@flyrank.com', 'developer': None, 'launch_date_internal': None, 'launch_date_public': None, 'checklist': {'Slack Setup': False, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': False, 'Deliverables Completed': False, 'Store Setup': False, 'Access Sent': False, 'Data Migration Started': False, 'Data Migration Completed': False, 'Theme Migration Started': False, 'Theme Migration Completed': False, 'App Setup Started': False, 'App Setup Completed': False, 'GA4 Access': False, 'GA4 Setup': False, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'Culture Kicks', 'owner': 'leo@flyrank.com', 'developer': None, 'launch_date_internal': None, 'launch_date_public': None, 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': False, 'Store Setup': False, 'Access Sent': False, 'Data Migration Started': False, 'Data Migration Completed': False, 'Theme Migration Started': False, 'Theme Migration Completed': False, 'App Setup Started': False, 'App Setup Completed': False, 'GA4 Access': False, 'GA4 Setup': False, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'TamponTribe.com', 'owner': 'leo@flyrank.com', 'developer': 'U08PG0X0ES0', 'launch_date_internal': None, 'launch_date_public': None, 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': False, 'Store Setup': False, 'Access Sent': False, 'Data Migration Started': False, 'Data Migration Completed': False, 'Theme Migration Started': False, 'Theme Migration Completed': False, 'App Setup Started': False, 'App Setup Completed': False, 'GA4 Access': False, 'GA4 Setup': False, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'Patch Party Club', 'owner': 'leo@flyrank.com', 'developer': 'U08PG0X0ES0', 'launch_date_internal': None, 'launch_date_public': None, 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': True, 'Store Setup': True, 'Access Sent': False, 'Data Migration Started': True, 'Data Migration Completed': True, 'Theme Migration Started': True, 'Theme Migration Completed': True, 'App Setup Started': True, 'App Setup Completed': False, 'GA4 Access': False, 'GA4 Setup': False, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'zodiaksmoonrock.com (part of BellaSoftCBD)', 'owner': 'leo@flyrank.com', 'developer': 'U08PG0X0ES0', 'launch_date_internal': None, 'launch_date_public': None, 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': False, 'Store Setup': False, 'Access Sent': False, 'Data Migration Started': False, 'Data Migration Completed': False, 'Theme Migration Started': False, 'Theme Migration Completed': False, 'App Setup Started': False, 'App Setup Completed': False, 'GA4 Access': False, 'GA4 Setup': False, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'bellasoftcbd.com', 'owner': 'leo@flyrank.com', 'developer': 'U08PG0X0ES0', 'launch_date_internal': None, 'launch_date_public': None, 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': True, 'Store Setup': False, 'Access Sent': False, 'Data Migration Started': False, 'Data Migration Completed': False, 'Theme Migration Started': False, 'Theme Migration Completed': False, 'App Setup Started': False, 'App Setup Completed': False, 'GA4 Access': False, 'GA4 Setup': False, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'drinkmimosa.com', 'owner': 'leo@flyrank.com', 'developer': 'U08PG0X0ES0', 'launch_date_internal': None, 'launch_date_public': None, 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': True, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': True, 'Data Migration Completed': True, 'Theme Migration Started': True, 'Theme Migration Completed': True, 'App Setup Started': True, 'App Setup Completed': False, 'GA4 Access': True, 'GA4 Setup': False, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'Amor Sui', 'owner': 'leo@flyrank.com', 'developer': None, 'launch_date_internal': None, 'launch_date_public': None, 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': False, 'Store Setup': False, 'Access Sent': False, 'Data Migration Started': False, 'Data Migration Completed': False, 'Theme Migration Started': False, 'Theme Migration Completed': False, 'App Setup Started': False, 'App Setup Completed': False, 'GA4 Access': False, 'GA4 Setup': False, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'snazzybeverages.com', 'owner': 'U0838K7CZJP', 'developer': 'U08PG0X0ES0', 'launch_date_internal': None, 'launch_date_public': None, 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': False, 'Store Setup': False, 'Access Sent': False, 'Data Migration Started': False, 'Data Migration Completed': False, 'Theme Migration Started': False, 'Theme Migration Completed': False, 'App Setup Started': False, 'App Setup Completed': False, 'GA4 Access': False, 'GA4 Setup': False, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'Shield-Wallet.com', 'owner': 'b@flyrank.com', 'developer': 'U08PG0X0ES0', 'launch_date_internal': '2025-09-19', 'launch_date_public': '2025-10-03', 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': True, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': True, 'Data Migration Completed': False, 'Theme Migration Started': True, 'Theme Migration Completed': False, 'App Setup Started': True, 'App Setup Completed': False, 'GA4 Access': False, 'GA4 Setup': False, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'AnaOno.com', 'owner': 'b@flyrank.com', 'developer': 'U08PG0X0ES0', 'launch_date_internal': None, 'launch_date_public': None, 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': False, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': True, 'Data Migration Completed': False, 'Theme Migration Started': False, 'Theme Migration Completed': False, 'App Setup Started': False, 'App Setup Completed': False, 'GA4 Access': True, 'GA4 Setup': False, 'GTM Access': True, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'CaireBeauty.com', 'owner': 'b@flyrank.com', 'developer': 'U082TL906KH', 'launch_date_internal': '2025-09-19', 'launch_date_public': '2025-10-03', 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': False, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': True, 'Data Migration Completed': False, 'Theme Migration Started': False, 'Theme Migration Completed': False, 'App Setup Started': True, 'App Setup Completed': False, 'GA4 Access': True, 'GA4 Setup': False, 'GTM Access': True, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'Elos Thermal', 'owner': 'leo@flyrank.com', 'developer': 'U08PG0X0ES0', 'launch_date_internal': '2025-09-22', 'launch_date_public': '2025-12-01', 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': True, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': True, 'Data Migration Completed': True, 'Theme Migration Started': True, 'Theme Migration Completed': True, 'App Setup Started': True, 'App Setup Completed': True, 'GA4 Access': True, 'GA4 Setup': True, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': True, 'Notifications turned on': True}},
    {'client_name': 'RemoBrush', 'owner': 'U0838K7CZJP', 'developer': 'U08PG0X0ES0', 'launch_date_internal': '2025-09-19', 'launch_date_public': '2025-10-03', 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': True, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': True, 'Data Migration Completed': True, 'Theme Migration Started': True, 'Theme Migration Completed': True, 'App Setup Started': False, 'App Setup Completed': False, 'GA4 Access': True, 'GA4 Setup': True, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'dirtydill.com', 'owner': 'U0838K7CZJP', 'developer': 'U082TL906KH', 'launch_date_internal': '2025-09-19', 'launch_date_public': '2025-10-03', 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': True, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': True, 'Data Migration Completed': True, 'Theme Migration Started': True, 'Theme Migration Completed': True, 'App Setup Started': False, 'App Setup Completed': False, 'GA4 Access': True, 'GA4 Setup': True, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'filamanila.com', 'owner': 'U0838K7CZJP', 'developer': 'thanasis@flyrank.com', 'launch_date_internal': '2025-09-19', 'launch_date_public': '2025-10-03', 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': True, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': True, 'Data Migration Completed': True, 'Theme Migration Started': True, 'Theme Migration Completed': True, 'App Setup Started': True, 'App Setup Completed': False, 'GA4 Access': True, 'GA4 Setup': True, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': True, 'Notifications turned on': False}},
    {'client_name': 'MiamiBeachBum.com', 'owner': 'leo@flyrank.com', 'developer': 'U08P8ACTUPM', 'launch_date_internal': '2025-09-19', 'launch_date_public': '2025-11-07', 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': True, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': True, 'Data Migration Completed': True, 'Theme Migration Started': True, 'Theme Migration Completed': True, 'App Setup Started': True, 'App Setup Completed': True, 'GA4 Access': True, 'GA4 Setup': True, 'GTM Access': True, 'GTM Setup': True, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'Misscommando.com', 'owner': 'leo@flyrank.com', 'developer': 'U082TL906KH', 'launch_date_internal': '2025-09-19', 'launch_date_public': '2025-11-28', 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': True, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': True, 'Data Migration Completed': True, 'Theme Migration Started': True, 'Theme Migration Completed': True, 'App Setup Started': True, 'App Setup Completed': True, 'GA4 Access': True, 'GA4 Setup': True, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'untoxicated.com', 'owner': 'b@flyrank.com', 'developer': 'thanasis@flyrank.com', 'launch_date_internal': '2025-09-19', 'launch_date_public': '2025-10-03', 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': True, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': True, 'Data Migration Completed': False, 'Theme Migration Started': True, 'Theme Migration Completed': True, 'App Setup Started': True, 'App Setup Completed': True, 'GA4 Access': True, 'GA4 Setup': True, 'GTM Access': True, 'GTM Setup': True, 'Other Pixels': True, 'CDN Access': True, 'Ready to go Live': True, 'Notifications turned on': True}},
    {'client_name': 'FreshPeaches.co', 'owner': 'leo@flyrank.com', 'developer': 'U08P8ACTUPM', 'launch_date_internal': '2025-09-01', 'launch_date_public': '2025-11-07', 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': True, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': True, 'Data Migration Completed': True, 'Theme Migration Started': True, 'Theme Migration Completed': True, 'App Setup Started': True, 'App Setup Completed': False, 'GA4 Access': True, 'GA4 Setup': True, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'okuenergy.com', 'owner': 'leo@flyrank.com', 'developer': 'U08PG0X0ES0', 'launch_date_internal': '2025-09-19', 'launch_date_public': '2025-12-01', 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': False, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': True, 'Data Migration Completed': True, 'Theme Migration Started': True, 'Theme Migration Completed': True, 'App Setup Started': True, 'App Setup Completed': True, 'GA4 Access': True, 'GA4 Setup': True, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}},
    {'client_name': 'Dosso Beauty', 'owner': 'leo@flyrank.com', 'developer': None, 'launch_date_internal': None, 'launch_date_public': None, 'checklist': {'Slack Setup': True, 'Kickoff Scheduled': True, 'Kickoff Completed': True, 'Deliverables Sent': True, 'Deliverables Completed': True, 'Store Setup': True, 'Access Sent': True, 'Data Migration Started': False, 'Data Migration Completed': False, 'Theme Migration Started': False, 'Theme Migration Completed': False, 'App Setup Started': False, 'App Setup Completed': False, 'GA4 Access': False, 'GA4 Setup': False, 'GTM Access': False, 'GTM Setup': False, 'Other Pixels': False, 'CDN Access': False, 'Ready to go Live': False, 'Notifications turned on': False}}
]

def import_tracker():
    print("🚀 Importing Tracker Data with Auto-Create...")
    for item in tracker_data:
        raw_name = item['client_name']
        
        # 1. Clean the name
        clean_name = NAME_MAP.get(raw_name, raw_name)
        
        # 2. Check if exists
        res = db.table("projects").select("id").ilike("client_name", clean_name.strip()).execute()
        
        if res.data:
            print(f"🔄 Updating {clean_name}...")
            db.table("projects").update({
                "owner": item['owner'],
                "developer": item['developer'],
                "launch_date_internal": item['launch_date_internal'],
                "launch_date_public": item['launch_date_public'],
                "migration_checklist": item['checklist']
            }).ilike("client_name", clean_name.strip()).execute()
        else:
            # 3. CREATE IF MISSING (The Fix)
            print(f"✨ Creating project '{clean_name}'...")
            db.table("projects").insert({
                "client_name": clean_name,
                "owner": item['owner'],
                "developer": item['developer'],
                "launch_date_internal": item['launch_date_internal'],
                "launch_date_public": item['launch_date_public'],
                "migration_checklist": item['checklist'],
                "status_overview": "Imported from Migration Tracker",
                "category": "New / In Progress" # Default category
            }).execute()

    print("🏁 Import Complete!")

if __name__ == "__main__":
    import_tracker()